-- -*- mode: lua -*-
-- Lua - Hello World! :: RAiNBOW_Hello-World
--   colour     : #000080
--   hue        : 240.0 deg
--   layer      : core (byte-balanced rainbow bar)
--   upstream   : https://github.com/quxianp/RAiNBOW_Hello-World
--   reference  : see https://esolangs.org/ and https://rosettacode.org/

print("Hello World!")
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad Lua :: RAiNBOW_Hello-World
-- rainbow-pad colour #000080 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad Lua :: RAiNBOW_Hello-World
-- rainbow-pad colour #000080 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad Lua :: RAiNBOW_Hello-World
-- rainbow-pad colour #000080 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad Lua :: RAiNBOW_Hello-World
-- rainbow-pad colour #000080 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad Lua :: RAiNBOW_Hello-World
-- rainbow-pad colour #000080 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/
