# Quake - Hello World! :: RAiNBOW_Hello-World
#   note       : Linguist recognises this language by filename, not by extension.
#   colour     : #882233
#   hue        : 350.0 deg
#   layer      : core (byte-balanced rainbow bar)
#   upstream   : https://github.com/quxianp/RAiNBOW_Hello-World
#   reference  : see https://esolangs.org/ and https://rosettacode.org/

# Hello World!
# Hello World!
