-- PLpgSQL - Hello World! :: RAiNBOW_Hello-World
--   note       : Linguist recognises this language by filename, not by extension.
--   colour     : #336790
--   hue        : 206.4 deg
--   layer      : core (byte-balanced rainbow bar)
--   upstream   : https://github.com/quxianp/RAiNBOW_Hello-World
--   reference  : see https://esolangs.org/ and https://rosettacode.org/

-- Hello World!
-- Hello World!
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad PLpgSQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #336790 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad PLpgSQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #336790 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad PLpgSQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #336790 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad PLpgSQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #336790 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad PLpgSQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #336790 :: padded to 100
             
