-- vim: set ft=hiveql:
--   note       : Pinned with a Linguist modeline so it keeps its own segment on the bar.
-- HiveQL - Hello World! :: RAiNBOW_Hello-World
--   colour     : #dce200
--   hue        : 61.6 deg
--   layer      : core (byte-balanced rainbow bar)
--   upstream   : https://github.com/quxianp/RAiNBOW_Hello-World
--   reference  : see https://esolangs.org/ and https://rosettacode.org/

-- Hello World!
-- Hello World!
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad HiveQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #dce200 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad HiveQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #dce200 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad HiveQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #dce200 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad HiveQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #dce200 :: padded to 100
-- rainbow-pad padding comment: byte balancing for the rainbow bar
-- rainbow-pad https://github.com/quxianp/RAiNBOW_Hello-World
-- rainbow-pad equal byte share keeps the language bar an even rainbow
-- rainbow-pad one segment per Linguist coloured language
-- rainbow-pad HiveQL :: RAiNBOW_Hello-World
-- rainbow-pad colour #dce200 :: padd
