[Roff Manpage] Hello World! :: RAiNBOW_Hello-World
  colour: #ecdebe
  layer : core
  upstream: https://github.com/quxianp/RAiNBOW_Hello-World
  reference: see https://esolangs.org/ and https://rosettacode.org/

.TH RAINBOW 1
.SH NAME
Hello World!








































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































