# Procfile - Hello World! :: RAiNBOW_Hello-World
#   colour     : #3b2f63
#   hue        : 253.8 deg
#   layer      : core (byte-balanced rainbow bar)
#   upstream   : https://github.com/quxianp/RAiNBOW_Hello-World
#   reference  : see https://esolangs.org/ and https://rosettacode.org/

web: echo "Hello World!"
